### ISSUE TITLE
update source code to match with implemented on FIS

### ISSUE THREAD

**Issue by tuannm1006** [FPT-Blockchain-Lab/quorum-middleware#65]
Features:

* create Standard/UPAS LC
* approve LC
* close LC
* submit amendment
* approve amendment
* fulfill amendment
* assign account role
* update account status
* generate message and sign message

**Comment by trmaphi** [comment]
https://github.com/FPT-Blockchain-Lab/quorum-middleware/pull/66

**Comment by trmaphi** [comment]
missing tests

**Comment by trmaphi** [comment]
https://github.com/FPT-Blockchain-Lab/quorum-middleware/pull/68
